name: Build Android APK (Debug)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools and platforms
        run: |
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          yes | sdkmanager --licenses

      # 1) Gera o Gradle Wrapper (o repo não tem os arquivos do wrapper)
      - name: Generate Gradle Wrapper (8.9)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          arguments: wrapper --gradle-version 8.9 --distribution-type bin

      # 2) Assegura permissão de execução
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 3) Valida o wrapper gerado (segurança/supply-chain)
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # 4) Build usando o wrapper recém-gerado
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      # 5) Publica o APK como artifact
      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
