name: Build Android APK/AAB

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools and platforms
        run: |
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          yes | sdkmanager --licenses

      # ⚠️ Em vez de SDKMAN/gradle wrapper manual, use a ação oficial do Gradle
      - name: Build Debug (APK)
        uses: gradle/gradle-build-action@v3
        with:
          # instala e usa exatamente essa versão de Gradle sem depender do wrapper
          gradle-version: 8.9
          arguments: assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
